name: 台股手機掃描

on:
  workflow_dispatch:
  schedule: 
      - cron: "10 6 * * 1-5"
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: 下載程式
        uses: actions/checkout@v4

      - name: 安裝 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 安裝套件
        run: pip install pandas requests openpyxl lxml

      - name: 執行股票掃描
        run: python stock_scanner_mobile.py
      - name: 保存選股結果
        uses: actions/upload-artifact@v4
        with:
          name: 今日選股結果
          path: "*.xlsx"
